/**
 * Re-copies the scoring kernel from the frontend repo and records its checksums.
 *
 *   node scripts/sync-kernel.mjs [path-to-gym-os]
 *
 * The kernel decides every number a user sees about their progress. The backend and
 * the browser must execute BYTE-IDENTICAL code: if the two copies drift, a member sees
 * one level on the leaderboard and a different one on their own tab, with nothing
 * failing and nobody able to say which is right.
 *
 * The two repos are separate, so a copy is unavoidable. What is avoidable is a SILENT
 * copy: kernel.checksums.json is committed, and kernel-parity.spec.ts fails the build
 * if the vendored files no longer match it. Editing the vendored copy directly turns
 * the suite red; syncing deliberately shows up as a checksum change in review.
 *
 * Never hand-edit anything in src/shared/scoring/ — change lib/*.js in the frontend,
 * run this, and commit both.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const rootDirectory = join(dirname(fileURLToPath(import.meta.url)), "..");
const targetDirectory = join(rootDirectory, "src", "shared", "scoring");
const manifestPath = join(targetDirectory, "kernel.checksums.json");

const KERNEL_FILES = ["scoring.js", "achievements.js", "levels.js"];

const sourceRoot = process.argv[2] || join(rootDirectory, "..", "gym-os");
const sourceDirectory = join(sourceRoot, "lib");

if (!fs.existsSync(sourceDirectory)) {
    console.error(`Frontend lib/ not found at ${sourceDirectory}.`);
    console.error("Pass the path explicitly: node scripts/sync-kernel.mjs ../gym-os");
    process.exit(1);
}

const checksums = {};
let changed = 0;

for (const file of KERNEL_FILES) {
    const source = join(sourceDirectory, file);
    if (!fs.existsSync(source)) {
        console.error(`Missing kernel source: ${source}`);
        process.exit(1);
    }
    const contents = fs.readFileSync(source);
    const target = join(targetDirectory, file);
    const existing = fs.existsSync(target) ? fs.readFileSync(target) : null;
    if (!existing || !existing.equals(contents)) {
        fs.writeFileSync(target, contents);
        changed += 1;
        console.log(`updated ${path.relative(rootDirectory, target)}`);
    }
    checksums[file] = createHash("sha256").update(contents).digest("hex");
}

fs.writeFileSync(manifestPath, JSON.stringify({
    "//": "Generated by scripts/sync-kernel.mjs. Do not hand-edit; edit the frontend lib/*.js and re-run.",
    syncedFrom: path.relative(rootDirectory, sourceDirectory).replace(/\\/g, "/"),
    files: checksums
}, null, 4) + "\n");

console.log(changed ? `synced ${changed} file(s)` : "already in sync");
console.log("checksums written to", path.relative(rootDirectory, manifestPath));
